# Generated by Django 3.2.6 on 2021-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenbis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
