# Generated by Django 3.2.9 on 2021-11-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=250)),
                ('size', models.PositiveBigIntegerField()),
                ('request_width', models.PositiveIntegerField(null=True)),
                ('request_height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attractions2.imageasset')),
            ],
            options={
                'unique_together': {('bucket', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attractions2.imageasset')),
            ],
        ),
    ]
