# Generated by Django 3.2.9 on 2021-11-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0002_attraction_museum_museumdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
