# Generated by Django 3.2.9 on 2021-11-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0004_attraction_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='region',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
