# Generated by Django 3.2.9 on 2021-11-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0005_auto_20211108_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='address',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
    ]
