# Generated by Django 3.2.9 on 2021-11-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0009_auto_20211112_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='last_visited',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 to='attractions2.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to='attractions2.googleuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created'], name='attractions_user_id_435c55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'attraction')},
        ),
    ]
