# Generated by Django 3.2.9 on 2021-11-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0011_auto_20211118_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitability',
            name='museum',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suitability',
            name='winery',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
