# Generated by Django 3.2.9 on 2021-11-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0012_auto_20211118_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('attraction_ptr', models.OneToOneField(auto_created=True,
                                                        on_delete=django.db.models.deletion.CASCADE,
                                                        parent_link=True, primary_key=True,
                                                        serialize=False,
                                                        to='attractions2.attraction')),
            ],
            bases=('attractions2.attraction',),
        ),
        migrations.AddField(
            model_name='suitability',
            name='zoo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
