# Generated by Django 3.2.9 on 2021-11-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0013_auto_20211120_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitability',
            name='trail',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('attraction_ptr', models.OneToOneField(auto_created=True,
                                                        on_delete=django.db.models.deletion.CASCADE,
                                                        parent_link=True, primary_key=True,
                                                        serialize=False,
                                                        to='attractions2.attraction')),
                ('difficulty',
                 models.CharField(choices=[('E', 'Easy'), ('N', 'Normal'), ('H', 'Hard')],
                                  max_length=1)),
                ('length', models.PositiveIntegerField()),
                ('elv_gain', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            to='attractions2.googleuser')),
            ],
            bases=('attractions2.attraction',),
        ),
    ]
