# Generated by Django 3.2.9 on 2021-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0015_alter_attraction_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
