# Generated by Django 3.2.9 on 2021-11-27 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0016_auto_20211127_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='suitability',
        ),
    ]
