# Generated by Django 3.2.9 on 2021-12-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('attractions2', '0017_remove_attraction_suitability'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='contenttypes.contenttype'),
        ),
    ]
