# Generated by Django 3.2.9 on 2021-12-04 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0018_attraction_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suitability',
        ),
    ]
