# Generated by Django 3.2.9 on 2021-12-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0019_delete_suitability'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffRoadTripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OffRoad',
            fields=[
                ('attraction_ptr', models.OneToOneField(auto_created=True,
                                                        on_delete=django.db.models.deletion.CASCADE,
                                                        parent_link=True, primary_key=True,
                                                        serialize=False,
                                                        to='attractions2.attraction')),
                ('trip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='attractions2.offroadtriptype')),
            ],
            bases=('attractions2.attraction',),
        ),
    ]
