# Generated by Django 3.2.9 on 2021-12-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0020_offroad_offroadtriptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='offroadtriptype',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
