# Generated by Django 3.2.9 on 2022-01-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0021_offroadtriptype_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('N', 'Normal'), ('H', 'Hard')], max_length=1)),
                ('length', models.PositiveIntegerField()),
                ('elv_gain', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('additional_images', models.ManyToManyField(related_name='trail_additional_image', to='attractions2.ImageAsset')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attractions2.imageasset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.googleuser')),
            ],
        ),
    ]
