# Generated by Django 3.2.9 on 2022-01-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0022_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
