# Generated by Django 3.2.9 on 2022-01-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0023_trail_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailUpload',
            fields=[
                ('date_modified', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('size', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.googleuser')),
            ],
        ),
    ]
