# Generated by Django 3.2.9 on 2022-01-05 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0024_trailupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailupload',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='trailupload',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
