# Generated by Django 3.2.9 on 2022-02-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0028_auto_20220211_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Trail Attractions',
            },
        ),
        migrations.AlterModelOptions(
            name='trailsuitability',
            options={'verbose_name_plural': 'Trail Suitabilities'},
        ),
    ]
