# Generated by Django 3.2.9 on 2022-02-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0030_auto_20220211_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museumdomain',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='offroadtriptype',
            options={'verbose_name_plural': 'Off-Road Trip Types'},
        ),
        migrations.AlterModelOptions(
            name='trailactivity',
            options={'verbose_name_plural': 'Trail Activities'},
        ),
        migrations.AlterModelOptions(
            name='trailattraction',
            options={'verbose_name_plural': 'Trail Attractions'},
        ),
        migrations.AlterModelOptions(
            name='trailsuitability',
            options={'verbose_name_plural': 'Trail Suitabilities'},
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='content_id',
            field=models.CharField(max_length=30),
        ),
    ]
