# Generated by Django 3.2.9 on 2022-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0031_auto_20220212_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='content_id',
            field=models.CharField(max_length=50),
        ),
    ]
