# Generated by Django 3.2.9 on 2022-03-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0034_auto_20220302_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageasset',
            unique_together={('parent_id', 'request_width', 'request_height'), ('bucket', 'key')},
        ),
    ]
