# Generated by Django 3.2.9 on 2022-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0035_alter_imageasset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
