# Generated by Django 3.2.9 on 2022-03-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0037_auto_20220311_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('additional_images', models.ManyToManyField(related_name='attraction_comment_image', to='attractions2.ImageAsset')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.googleuser')),
            ],
        ),
    ]
