# Generated by Django 3.2.9 on 2022-03-11 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0038_attractioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractioncomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 11, 15, 2, 12, 409523)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attractioncomment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='attractioncomment',
            index=models.Index(fields=['attraction', '-created'], name='attractions_attract_16cf48_idx'),
        ),
    ]
