# Generated by Django 3.2.9 on 2022-03-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions2', '0039_auto_20220311_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractioncomment',
            old_name='additional_images',
            new_name='images',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
    ]
