# Generated by Django 3.2.9 on 2022-03-19 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0041_alter_attractioncomment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trail',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='trail',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TrailComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(related_name='trail_comment_image', to='attractions2.ImageAsset')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.googleuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='trailcomment',
            index=models.Index(fields=['trail', '-created'], name='attractions_trail_i_df9bd2_idx'),
        ),
    ]
