# Generated by Django 3.2.9 on 2022-03-22 16:08

import django.db.models.deletion
from django.db import migrations, models


def _migrate_model(model_name: str) -> migrations.RunSQL:
    return migrations.RunSQL(f"""UPDATE attractions2_{model_name}
            SET 
                _address = attractions.address,
                 _city = attractions.city,
                 _description = attractions.description,
                 _region_id = attractions.region_id,
                 _telephone = attractions.telephone,
                 _website = attractions.website
            FROM attractions2_attraction as attractions
            WHERE attraction_ptr_id = attractions.id""")


def rename_fields(model_name: str):
    result = []

    for column in ["address", "city", "description", "region", "telephone", "website"]:
        result.append(migrations.RenameField(
            model_name=model_name,
            old_name="_" + column,
            new_name=column
        ))

    return result


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0042_auto_20220319_1717'),
    ]

    operations = [
                     migrations.AddField(
                         model_name='museum',
                         name='_address',
                         field=models.CharField(default='', max_length=150),
                         preserve_default=False,
                     ),
                     migrations.AddField(
                         model_name='museum',
                         name='_city',
                         field=models.CharField(blank=True, max_length=50, null=True),
                     ),
                     migrations.AddField(
                         model_name='museum',
                         name='_description',
                         field=models.TextField(blank=True, null=True),
                     ),
                     migrations.AddField(
                         model_name='museum',
                         name='_region',
                         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='attractions2.region'),
                     ),
                     migrations.AddField(
                         model_name='museum',
                         name='_telephone',
                         field=models.CharField(blank=True, max_length=10, null=True),
                     ),
                     migrations.AddField(
                         model_name='museum',
                         name='_website',
                         field=models.URLField(blank=True, null=True),
                     ),
                     _migrate_model("museum"),
                     migrations.AddField(
                         model_name='offroad',
                         name='_address',
                         field=models.CharField(default='', max_length=150),
                         preserve_default=False,
                     ),
                     migrations.AddField(
                         model_name='offroad',
                         name='_city',
                         field=models.CharField(blank=True, max_length=50, null=True),
                     ),
                     migrations.AddField(
                         model_name='offroad',
                         name='_description',
                         field=models.TextField(blank=True, null=True),
                     ),
                     migrations.AddField(
                         model_name='offroad',
                         name='_region',
                         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='attractions2.region'),
                     ),
                     migrations.AddField(
                         model_name='offroad',
                         name='_telephone',
                         field=models.CharField(blank=True, max_length=10, null=True),
                     ),
                     migrations.AddField(
                         model_name='offroad',
                         name='_website',
                         field=models.URLField(blank=True, null=True),
                     ),
                     _migrate_model("offroad"),
                     migrations.AddField(
                         model_name='rockclimbing',
                         name='_address',
                         field=models.CharField(default='', max_length=150),
                         preserve_default=False,
                     ),
                     migrations.AddField(
                         model_name='rockclimbing',
                         name='_city',
                         field=models.CharField(blank=True, max_length=50, null=True),
                     ),
                     migrations.AddField(
                         model_name='rockclimbing',
                         name='_description',
                         field=models.TextField(blank=True, null=True),
                     ),
                     migrations.AddField(
                         model_name='rockclimbing',
                         name='_region',
                         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='attractions2.region'),
                     ),
                     migrations.AddField(
                         model_name='rockclimbing',
                         name='_telephone',
                         field=models.CharField(blank=True, max_length=10, null=True),
                     ),
                     migrations.AddField(
                         model_name='rockclimbing',
                         name='_website',
                         field=models.URLField(blank=True, null=True),
                     ),
                     _migrate_model("rockclimbing"),
                     migrations.AddField(
                         model_name='watersports',
                         name='_address',
                         field=models.CharField(default='', max_length=150),
                         preserve_default=False,
                     ),
                     migrations.AddField(
                         model_name='watersports',
                         name='_city',
                         field=models.CharField(blank=True, max_length=50, null=True),
                     ),
                     migrations.AddField(
                         model_name='watersports',
                         name='_description',
                         field=models.TextField(blank=True, null=True),
                     ),
                     migrations.AddField(
                         model_name='watersports',
                         name='_region',
                         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='attractions2.region'),
                     ),
                     migrations.AddField(
                         model_name='watersports',
                         name='_telephone',
                         field=models.CharField(blank=True, max_length=10, null=True),
                     ),
                     migrations.AddField(
                         model_name='watersports',
                         name='_website',
                         field=models.URLField(blank=True, null=True),
                     ),
                     _migrate_model("watersports"),
                     migrations.AddField(
                         model_name='winery',
                         name='_address',
                         field=models.CharField(default='', max_length=150),
                         preserve_default=False,
                     ),
                     migrations.AddField(
                         model_name='winery',
                         name='_city',
                         field=models.CharField(blank=True, max_length=50, null=True),
                     ),
                     migrations.AddField(
                         model_name='winery',
                         name='_description',
                         field=models.TextField(blank=True, null=True),
                     ),
                     migrations.AddField(
                         model_name='winery',
                         name='_region',
                         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='attractions2.region'),
                     ),
                     migrations.AddField(
                         model_name='winery',
                         name='_telephone',
                         field=models.CharField(blank=True, max_length=10, null=True),
                     ),
                     migrations.AddField(
                         model_name='winery',
                         name='_website',
                         field=models.URLField(blank=True, null=True),
                     ),
                     _migrate_model("winery"),
                     migrations.AddField(
                         model_name='zoo',
                         name='_address',
                         field=models.CharField(default='', max_length=150),
                         preserve_default=False,
                     ),
                     migrations.AddField(
                         model_name='zoo',
                         name='_city',
                         field=models.CharField(blank=True, max_length=50, null=True),
                     ),
                     migrations.AddField(
                         model_name='zoo',
                         name='_description',
                         field=models.TextField(blank=True, null=True),
                     ),
                     migrations.AddField(
                         model_name='zoo',
                         name='_region',
                         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='attractions2.region'),
                     ),
                     migrations.AddField(
                         model_name='zoo',
                         name='_telephone',
                         field=models.CharField(blank=True, max_length=10, null=True),
                     ),
                     migrations.AddField(
                         model_name='zoo',
                         name='_website',
                         field=models.URLField(blank=True, null=True),
                     ),
                     _migrate_model("zoo"),
                     migrations.AlterField(
                         model_name='region',
                         name='name',
                         field=models.CharField(max_length=200),
                     ),
                     migrations.AlterModelOptions(
                         name='region',
                         options={'ordering': ['name']},
                     ),
                     migrations.RemoveField(
                         model_name='attraction',
                         name='address',
                     ),
                     migrations.RemoveField(
                         model_name='attraction',
                         name='city',
                     ),
                     migrations.RemoveField(
                         model_name='attraction',
                         name='description',
                     ),
                     migrations.RemoveField(
                         model_name='attraction',
                         name='region',
                     ),
                     migrations.RemoveField(
                         model_name='attraction',
                         name='telephone',
                     ),
                     migrations.RemoveField(
                         model_name='attraction',
                         name='website',
                     ),
                     migrations.RemoveField(
                         model_name='region',
                         name='image',
                     ),
                 ] + rename_fields("museum") + rename_fields("offroad") + rename_fields("rockclimbing") + \
                 rename_fields("watersports") + rename_fields("winery") + rename_fields("zoo")
