# Generated by Django 3.2.9 on 2022-03-22 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0043_auto_20220322_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailcomment',
            name='images',
        ),
        migrations.RemoveField(
            model_name='trailcomment',
            name='trail',
        ),
        migrations.RemoveField(
            model_name='trailcomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='trailfavorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trailfavorite',
            name='trail',
        ),
        migrations.RemoveField(
            model_name='trailfavorite',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='trailhistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trailhistory',
            name='trail',
        ),
        migrations.RemoveField(
            model_name='trailhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trail',
        ),
        migrations.DeleteModel(
            name='TrailComment',
        ),
        migrations.DeleteModel(
            name='TrailFavorite',
        ),
        migrations.DeleteModel(
            name='TrailHistory',
        ),
    ]
