# Generated by Django 3.2.9 on 2022-03-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0044_auto_20220322_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('attraction_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='attractions2.attraction')),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('N', 'Normal'), ('H', 'Hard')], max_length=1)),
                ('length', models.PositiveIntegerField()),
                ('elv_gain', models.PositiveIntegerField()),
                ('activities',
                 models.ManyToManyField(related_name='trails_with_activity', to='attractions2.TrailActivity')),
                ('attractions',
                 models.ManyToManyField(related_name='trails_with_attraction', to='attractions2.TrailAttraction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.googleuser')),
                ('suitabilities',
                 models.ManyToManyField(related_name='suitable_trails', to='attractions2.TrailSuitability')),
            ],
            bases=('attractions2.attraction',),
        ),
    ]
