# Generated by Django 3.2.9 on 2022-03-28 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0045_trail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtremeSportsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='attraction',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='attraction_additional_image',
                                         to='attractions2.ImageAsset'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='trails_with_activity',
                                         to='attractions2.TrailActivity'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='trails_with_attraction',
                                         to='attractions2.TrailAttraction'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='suitabilities',
            field=models.ManyToManyField(blank=True, related_name='suitable_trails',
                                         to='attractions2.TrailSuitability'),
        ),
        migrations.CreateModel(
            name='ExtremeSports',
            fields=[
                ('attraction_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='attractions2.attraction')),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('region',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attractions2.region')),
            ],
            options={
                'abstract': False,
            },
            bases=('attractions2.attraction',),
        ),
    ]
