# Generated by Django 3.2.9 on 2022-03-30 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0046_auto_20220328_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='extremesports',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.extremesportstype'),
            preserve_default=False,
        ),
    ]
