# Generated by Django 3.2.9 on 2022-04-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0047_extremesports_sport_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotAir',
            fields=[
                ('attraction_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='attractions2.attraction')),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('region',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attractions2.region')),
            ],
            options={
                'abstract': False,
            },
            bases=('attractions2.attraction',),
        ),
    ]
