# Generated by Django 3.2.9 on 2022-04-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0049_overnight_package_startlocation_tour_tourdestination_tourlanguage_tourtheme_tourtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourtype',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='attractions2.imageasset'),
        ),
    ]
