# Generated by Django 3.2.9 on 2022-04-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0050_alter_tourtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overnight',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='attractions2.imageasset'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='attractions2.imageasset'),
        ),
        migrations.AlterField(
            model_name='tourtheme',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='attractions2.imageasset'),
        ),
    ]
