# Generated by Django 3.2.9 on 2022-05-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0051_auto_20220412_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.tour')),
            ],
            options={
                'unique_together': {('tour', 'day')},
            },
        ),
    ]
