# Generated by Django 3.2.9 on 2022-05-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0054_auto_20220509_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touravailability',
            name='booked',
        ),
        migrations.CreateModel(
            name='TourReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_confirmation_id', models.CharField(max_length=50)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions2.googleuser')),
            ],
        ),
    ]
