# Generated by Django 3.2.9 on 2022-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0055_auto_20220509_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tourtype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_type',
        ),
        migrations.DeleteModel(
            name='TourTheme',
        ),
        migrations.DeleteModel(
            name='TourType',
        ),
        migrations.AddField(
            model_name='tour',
            name='destinations',
            field=models.ManyToManyField(to='attractions2.TourDestination'),
        ),
    ]
