# Generated by Django 3.2.9 on 2022-05-10 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0056_auto_20220510_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_location',
        ),
        migrations.DeleteModel(
            name='StartLocation',
        ),
    ]
