# Generated by Django 3.2.9 on 2022-05-14 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0057_auto_20220510_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourreservation',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tourreservation',
            name='last_name',
        ),
    ]
