# Generated by Django 3.2.9 on 2022-05-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attractions2', '0058_auto_20220514_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreservation',
            name='group',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='tourreservation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
