# Generated by Django 3.2.6 on 2021-11-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_review', '0004_notablefeature_images'),
        ('attractions', '0003_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='additional_images',
            field=models.ManyToManyField(related_name='attraction_additional_image', to='market_review.ImageAsset'),
        ),
    ]
