# Generated by Django 3.2.6 on 2021-08-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=250)),
                ('size', models.PositiveBigIntegerField()),
                ('request_width', models.PositiveIntegerField(null=True)),
                ('request_height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_review.imageasset')),
            ],
            options={
                'unique_together': {('bucket', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=250)),
                ('long_name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField()),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_review.imageasset')),
            ],
        ),
    ]
