# Generated by Django 3.2.6 on 2021-08-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_review.imageasset'),
        ),
        migrations.CreateModel(
            name='NotableFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_review.application')),
            ],
            options={
                'unique_together': {('app', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_review.notablefeature')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_review.imageasset')),
            ],
            options={
                'unique_together': {('feature', 'image')},
            },
        ),
    ]
