# Generated by Django 3.2.6 on 2021-08-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_review', '0002_auto_20210808_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_review.application')),
            ],
            options={
                'unique_together': {('app', 'slug')},
            },
        ),
    ]
