# Generated by Django 3.2.6 on 2021-08-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_review', '0003_missingfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='notablefeature',
            name='images',
            field=models.ManyToManyField(through='market_review.FeatureImage', to='market_review.ImageAsset'),
        ),
    ]
